# 启用自动更新功能
auto-update: true

# 启用 LiteXpansion 整合
# LiteXpansion 物品将用于 FN 发电机的配方中
# 仅在该设置为 true 且服务器已安装 LiteXpansion 时生效
LiteX-Recipe-Integration: true

# 启用 SMG(SimpleMaterialGenerators) 整合
# SMG 物品将用于 FN 材料发电机的部分配方中
# 仅在该设置为 true 且服务器已安装 SMG 时生效
SMG-Recipe-Integration: true

# 启用 1.17 整合
# 使用 1.17 物品作为 FN 机器的配方
# 仅在该设置为 true 且服务器版本为 1.17 及以上时生效
New-Recipe-Integration: true

# Armor Effects Update，以秒为单位更新装甲效果的时间（即 FN Gears of Friction 永久效果）
# 目前胸甲只在30级有永久效果
armor-update-period: 10

# 启用或禁用聊天更新日志，此更新日志仅在服务器重启后玩家第一次加入服务器时发送
# 如果禁用，将不再发送更改日志，需要重新启动服务器
Enable-One-Time-Chat-Changelog: true
