name: FNAmplifications
version: '${project.version}'
main: ne.fnfal113.fnamplifications.FNAmplifications
api-version: 1.15
authors: [ FN_FAL113,wateTina ]
description: 自定义插件，包括我的其他 slimefun 插件
website: https://github.com/FN-FAL113
depend: [Slimefun]
softdepend:
  - LiteXpansion
  - SimpleMaterialGenerators
  - Vault
commands:
  fngear:
    description: 检查 FN Gears 进度的命令
    default: true
    usage: /<command>
  fngear.levelupgears:
    description: Command for levelling up FN Gears
    usage: /<command>
    default: op
