name: Java CI

on:
  push:
    branches:
    - main
    tags:
      - "v*.*"
  pull_request:
    branches:
    - main
    
jobs:
  create_release:
    name: "创建发布"
    needs: [build]
    if: startsWith(github.ref, 'refs/tags/v')

    runs-on: ubuntu-latest
    steps:
    - name: 下载构建
      uses: actions/download-artifact@v2.1.0
      with:
        path: etc/usr/artifacts/
        
    - name: 创建发布
      uses: softprops/action-gh-release@v0.1.14
      with:
        draft: true
        fail_on_unmatched_files: true
        files: |
          home/runner/work/FN-FAL-s-Amplifications-zh/FN-FAL-s-Amplifications-zh/etc/usr/artifacts/FNAmplifications/*
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2.3.3
    - name: Set up JDK 17
      uses: actions/setup-java@v1.4.3
      with:
        java-version: 17
    - name: Build with Maven
      run: mvn package --file pom.xml
    - name: 自动释放
      uses: marvinpinto/action-automatic-releases@v1.2.1
      with:
        repo_token: "${{ secrets.GITHUB_TOKEN }}"
        automatic_release_tag: "jar"
        prerelease: true
        title: "FNAmplifications 自动构建版本"
        files: |
           target/*
    - name: Upload The Bruh
      uses: actions/upload-artifact@v2
      with:
        name: FNAmplifications
        path: |
           target/*